export {default as BlogPage} from "./blog"
export {default as ContactUs} from "./contactus"
export {default as  Aboutuscomponent} from "./aboutus"
export {default as  Aboutcomponent} from "./about"
export {default as  Headercomponent} from "./header"
export {default as  Trainingcomponent} from "./Training"
export {default as  Footer} from "../components/footer"
export {default as  Navbar} from "../components/navbar"
export {default as  BlogPageonecomponent} from "../components/blogcomponentone"
export {default as BlogNewscomponent} from "../components/blogNews"
export {default as MainBlog } from "./mainblog"